name: 'Set PR description'
description: 'Analyse all merge commits in PR and creates change-notes based on child PR's names'
inputs:
  github-token:  # id of input
    description: 'Github api token if you want to fetch private repo'
    required: true
    default: ''
  github-user-name:
    description: 'Github user name'
    required: false
    default: ''
  github-user-email:
    description: 'Github user email'
    required: false
    default: ''
outputs:
  time: # id of output
    description: 'The time action is finished to do it's job'
runs:
  using: 'node12'
  main: 'dist/index.js'